- name: "K8s Kube-Proxy CSR configuration-file provisioning"
  ansible.builtin.template:
    src: "k8s/worker/k8s-kube-proxy-cert-csr.json.j2"
    dest: "{{ k8s_ca_certificate_conf_directory }}/k8s-kube-proxy-cert-csr.json"
    owner: "{{ k8s_ca_certificate_owner }}"
    group: "{{ k8s_ca_certificate_group }}"
    mode: "{{ k8s_ca_certificate_file_perm }}"

- name: "K8s Kube-Proxy Certificate provisioning"
  ansible.builtin.shell: >
    set -o errexit; \
    set -o pipefail; \
    cfssl gencert \
      -config=k8s-ca-config.json \
      -profile=kubernetes \
      -ca=k8s-ca.pem \
      -ca-key=k8s-ca-key.pem \
      k8s-kube-proxy-cert-csr.json \
    | cfssljson -bare k8s-kube-proxy
  args:
    executable: "/bin/bash"
    chdir: "{{ k8s_ca_certificate_conf_directory }}"
    creates: "{{ k8s_ca_certificate_conf_directory }}/k8s-kube-proxy-key.pem"

- name: "K8s Kube-Proxy Certificate files permissions"
  ansible.builtin.file:
    path: "{{ k8s_ca_certificate_conf_directory }}/{{ item }}"
    owner: "{{ k8s_ca_certificate_owner }}"
    group: "{{ k8s_ca_certificate_group }}"
    mode: '{{ k8s_ca_certificate_file_perm }}'
    modification_time: "preserve"
    access_time: "preserve"
  loop:
    - k8s-kube-proxy.pem
    - k8s-kube-proxy-key.pem
    - k8s-kube-proxy.csr

- name: "K8s Kube-Proxy PKI files copying"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ k8s_ca_certificate_conf_directory }}/{{ item.src_file }}"
    dest: "{{ k8s_worker_pki_directory }}/{{ item.dest_file }}"
    owner: "{{ k8s_pki_admin_user }}"
    group: "{{ k8s_pki_admin_group }}"
    mode: '{{ k8s_ca_certificate_file_perm }}'
  loop:
    - { src_file: 'k8s-kube-proxy.pem', dest_file: 'kube-proxy.crt' }
    - { src_file: 'k8s-kube-proxy-key.pem', dest_file: 'kube-proxy.key' }
