- name: "APT update package cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  retries: 2
  delay: 5

- name: "APT autoremove"
  ansible.builtin.apt:
    autoremove: true
  retries: 2
  delay: 5
  tags:
    - apt

- name: "APT upgrade to the latest packages"
  ansible.builtin.apt:
    upgrade: safe
    autoremove: true
  retries: 2
  delay: 5

- name: "APT adjust update intervals"
  ansible.builtin.copy:
    src: apt-periodic
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: "0644"

# TODO: Install common utilities
