# Downloading the binaries into a temporary directory -> Copying to the permanent location

- name: "ETCD download directory initialization"
  ansible.builtin.file:
    path: "{{ etcd_download_dir }}"
    state: directory

- name: "ETCD downloading the binary archive"
  ansible.builtin.get_url:
    url: "{{ etcd_download_url }}"
    dest: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-{{ etcd_os }}-{{ etcd_arch }}.tar.gz"
    checksum: "{{ etcd_download_url_checksum }}"
    mode: "0755"

- name: "ETCD extracting the binary archive"
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-{{ etcd_os }}-{{ etcd_arch }}.tar.gz"
    dest: "{{ etcd_download_dir }}/"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    creates: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-{{ etcd_os }}-{{ etcd_arch }}/etcd"
  tags:
    - etcd

- name: "ETCD binaries copying"
  ansible.builtin.copy:
    src: "{{ etcd_download_dir }}/etcd-v{{ etcd_version }}-{{ etcd_os }}-{{ etcd_arch }}/{{ item }}"
    dest: "{{ etcd_bin_dir }}/{{ item }}"
    mode: "0755"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    remote_src: true
  with_items:
    - etcd
    - etcdctl
