- name: "ETCD data directory creation"
  ansible.builtin.file:
    state: directory
    path: "{{ etcd_data_dir }}"
    mode: "{{ etcd_data_dir_mode }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"

- name: "ETCD SystemD service-file provisioning"
  ansible.builtin.template:
    src: etcd.service.j2
    dest: "/etc/systemd/system/{{ etcd_service_name }}.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Reload systemd

# Ensuring that SystemD is reloaded and ETCD service is running
- name: "Flushing handlers"
  ansible.builtin.meta: flush_handlers

- name: "ETCD SystemD service activation"
  ansible.builtin.service:
    name: "{{ etcd_service_name }}"
    enabled: true
    state: started
