- name: "K8s Scheduler configuration directory setup"
  ansible.builtin.file:
    path: "{{ k8s_scheduler_conf_dir }}"
    owner: "{{ k8s_user }}"
    group: "{{ k8s_group }}"
    mode: "{{ k8s_conf_dir_mode }}"
    state: directory

- name: "K8s Scheduler kube-config authentication setup"
  ansible.builtin.include_tasks:
    file: "scheduler/scheduler-auth.yaml"

- name: "K8s Scheduler SystemD service-file provisioning"
  ansible.builtin.template:
    src: systemd/kube-scheduler.service.j2
    dest: "/etc/systemd/system/{{ k8s_scheduler_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart kube-scheduler

- name: "K8s Scheduler SystemD service activation"
  ansible.builtin.service:
    name: "{{ k8s_scheduler_service_name }}"
    enabled: true
    state: started
