- name: "K8s Worker Kube-Proxy configuration directory setup"
  ansible.builtin.file:
    path: "{{ k8s_worker_kubeproxy_conf_dir }}"
    owner: "{{ k8s_worker_user }}"
    group: "{{ k8s_worker_group }}"
    mode: "{{ k8s_worker_conf_dir_mode }}"
    state: directory

- name: "K8s Worker Kube-Proxy kube-config authentication setup"
  ansible.builtin.include_tasks:
    file: "kube-proxy/kube-proxy-auth.yaml"

- name: "K8s Worker Kube-Proxy configuration file provisioning"
  ansible.builtin.template:
    src: kubernetes/kube-proxy-config.yaml.j2
    dest: "{{ k8s_worker_kubeproxy_conf_file }}"
    owner: "{{ k8s_worker_user }}"
    group: "{{ k8s_worker_group }}"
    mode: "{{ k8s_worker_conf_file_mode }}"

- name: "K8s Worker Kube-Proxy SystemD service-file provisioning"
  ansible.builtin.template:
    src: systemd/kube-proxy.service.j2
    dest: "/etc/systemd/system/{{ k8s_kubeproxy_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart kube-proxy

- name: "K8s Worker Kube-Proxy SystemD service activation"
  ansible.builtin.service:
    name: "{{ k8s_kubeproxy_service_name }}"
    enabled: true
    state: started
