#
# K8s Worker-Node user
#

# SUPER-IMPORTANT: All K8s Worker processes need to run as root / admin and have complete access to the node
k8s_worker_user: "root"
k8s_worker_group: "root"

#
# Configuration files
#

k8s_worker_conf_base_dir: "/etc/kubernetes/worker"

k8s_worker_pki_dir: "{{ k8s_worker_conf_base_dir }}/pki"

# TODO: Get rid of?
k8s_worker_ca_dir: "{{ k8s_worker_conf_base_dir }}/ca"

k8s_worker_conf_dir_mode: "0750"
k8s_worker_conf_file_mode: "0660"

#
# K8s Control-Plane
#

k8s_worker_api_endpoint: "https://{{ k8s_control_plane_node_public_ip }}:6443"

#
# OS-Packages needed by the K8s Worker to run properly (Alongside the binaries)
#

k8s_worker_os_packages:
  - ebtables
  - ethtool
  - ipset
  - conntrack
  - iptables
  - iptstate
  - netstat-nat
  - socat
  - netbase

#
# K8s Worker binaries
#

k8s_worker_release: "1.27.15"

k8s_worker_arch: "amd64"
k8s_worker_os: "linux"

k8s_worker_binaries:
  - kubelet
  - kube-proxy
  # Important: Needed for provisioning kubeconfig files for kube-proxy and kubelet
  - kubectl

k8s_worker_bin_dir: "/usr/local/bin"

#
# K8s kube-config files
#

k8s_worker_kube_config_file_mode: "0640"

#
# K8s Worker services settings (Common)
#

k8s_worker_service_options:
  - User={{ k8s_worker_user }}
  - Group={{ k8s_worker_group }}
  - Restart=always
  - RestartSec=5
