k8s_kubeproxy_service_name: "kube-proxy"

k8s_worker_kubeproxy_conf_dir: "{{ k8s_worker_conf_base_dir }}/kube-proxy"
k8s_worker_kubeproxy_conf_file: "{{ k8s_worker_kubeproxy_conf_dir }}/kubeproxy-config.yaml"
k8s_worker_kubeproxy_kubeconfig: "{{ k8s_worker_kubeproxy_conf_dir }}/kubeconfig"

k8s_worker_kubeproxy_settings:
  # IMPORTANT: Making sure the hostname of the node is the one specified in the rest of the configuration
  "hostname-override": "{{ k8s_worker_node_hostname }}"
  "config": "{{ k8s_worker_kubeproxy_conf_file }}"

k8s_worker_kubeproxy_service_options:
  # Allowing Kubelet to use up to 150MB
  - MemoryMax=150M
  # Setting Kubelet CPU-Weight to that of a regular service (100 is the SystemD default)
  - CPUWeight=100
